# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  macOS-15:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  Ubuntu-latest:
    strategy:
      matrix:
        swift:
          - '6.0.2'
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
